### ISSUE TITLE
Need to replace reciprocal score conversion before weekend

### ISSUE THREAD

**Issue by redavids** [agupta0905/AGBsvdquartets#3]
Dear SVD Group:

Shashank called me today to talk about preparing for his class presentation, and his questions about the theory behind this method led us to some important realizations, that impact corrections that should be make to score conversions before we run things this weekend.

In particular, we should not use the function 1/x to convert the SVD scores for wQMC, because the theory predicts that if the frequencies in the data are close enough to the true probability distribution, the SVD score for the best split will be zero!   I.E. x = 0 is something we should expect to deal with.  

So, exp(-x) or exp(-x^p) for some p > 1 (which is 1 when x = 0 and is decreasing....)  would be a good model function to replace 1/x with before the experiments you all were planning to run over the weekend take place. 

I believe Jed had mentioned trying this earlier as a conversion and it got lost in the shuffle.

Another thing to expect is that is the frequencies in the gene data are not good enough approximations to the true probability distribution, it may be the case that all three scores are zero.  We need to decide what to do in this case.  Shashank suggested that perhaps we could give equal weight to all but reduce it somehow to reflect that we had no confidence in any of them.  
1.  In the case where there is only one zero, and two nonzero scores, our mapping function of course should give highest value to that.  
2.  If all the tree scores are zero, the approximation of frequencies to probabilities  not very good, we should give a very low weight to all three quartets on a four taxon subset before feeding to wQMC.  

Please do not hesitate to contact me today or tomorrow about this, and I am going to post this as an issue to Ashu's github too.   

Best
Ruth

**Comment by syadu1988** [comment]
Hi everybody

How about power(e,-svdscore)/(No of quartets with score 0) ?

**Comment by syadu1988** [comment]
Actually 11C4 is 330 while 11^2.8 is about 824. Maybe thats a possible problem why wqmc won’t give good results?

And in that case removing certain quartets further will make it worse. 

P.S. Jed lets discuss here so its documented in GitHub too.

**Comment by j-chou** [comment]
Ah you're right. I still think maybe we should discard the quartets if svd_max = 0 because they are uninformative. wQMC should still be able to infer the correct relationship from the other quartets whose taxa set intersects the discarded quartets taxa set.

**Comment by redavids** [comment]
I like the idea of discarding quartets with equal scores for this weekend's
experiment.  Another issue that I'm not sure got emphasized enough is
that-aside from discarding all the equal-scoring quartets- _we should be
using all of the rest of the quartets instead of subsampling_.  It should
be no problem to use all 11 choose 4 = 330 quartets for these simulated
data sets.

Thanks everyone!  I'm really enjoying this project.

On Thu, Apr 9, 2015 at 9:13 PM, j-chou notifications@github.com wrote:

> Ah you're right. I still think maybe we should discard the quartets if
> svd_max = 0 because they are uninformative. wQMC should still be able to
> infer the correct relationship from the other quartets whose taxa set
> intersects the discarded quartets taxa set.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agupta0905/AGBsvdquartets/issues/3#issuecomment-91402027
> .

## 

Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/

**Comment by syadu1988** [comment]
Also,

should we discard the quartets if 2 of the scores are 0 and one is non zero?

Secondly, there are cases where WQMC doesn’t return anything. I am not sure what the reason is but Ashu suggests that maybe its because the weights become too large on some occasions. Looking at the WQMC paper formula, that formula only makes sense from the perspective of distances, not SVD scores. Hence e^(-svd_score) again i think makes sense because it will assign 1 to zero svd scores and some <1 scores to higher svd scores.Infact I would suggest that we should try several other factors such as 10^(-svd_score) because higher the alpha is in alpha^(-svd_score), the more separation we will get. So we should play around with this factor.

P.S.

Jed, there is an error in the formula you have used in A and D. The score should be high - low in the numerator, not med-low. Please call me if you are awake right now or when you wake up tomorrow.

Thanks
Shashank
