### ISSUE TITLE
15-taxon dataset processsing

### ISSUE THREAD

**Issue by j-chou** [agupta0905/AGBsvdquartets#6]
The 15-taxon dataset (caterpillar model species tree generated with MCcoal) (http://www.cs.utexas.edu/~phylo/datasets/binning-response/) has gene alignments in fasta format. We need to convert this to phylip format before running the other processing scripts. Ruth, I think you mentioned dendropy has this functionality?

**Comment by redavids** [comment]
Now I am not sure if Dendropy can handle gene alignments, maybe it just
handles trees:

https://pythonhosted.org/DendroPy/tutorial/converting.html

Spend a few minutes searching the Dendropy library API.  There is also this
tool, which is what I'd look at first since I like python:

https://pypi.python.org/pypi/bioscripts.convert/0.4

And I just found this by googling:

http://sequenceconversion.bugaco.com/converter/biology/sequences/fasta_to_phylip.php

There must be zillion tools for this,

You should ask Nam or Siavash what they would use too. Or just google.
Sorry!  This is not something I've ever actually done so I just assumed
Dendropy would convert alignments-maybe it does.  I don't have time to
search the API right now.

Best
R

On Wed, Apr 22, 2015 at 1:39 PM, j-chou notifications@github.com wrote:

> The 15-taxon dataset (caterpillar model species tree generated with
> MCcoal) (http://www.cs.utexas.edu/~phylo/datasets/binning-response/) has
> gene alignments in fasta format. We need to convert this to phylip format
> before running the other processing scripts. Ruth, I think you mentioned
> dendropy has this functionality?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agupta0905/AGBsvdquartets/issues/6.

## 

Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/

**Comment by j-chou** [comment]
Ok, thanks Ruth! The one you linked to, Fast2Phylip.pl, works, so I'll try to get it done tomorrow.

**Comment by syadu1988** [comment]
Hi Jed

Dendropy can handle Fasta data and it should just involve adding two lines to the taxon_relabeler.py script. Ashu or I have already made that change this morning so Ashu can discuss this with you after the class today. (I won’t be able to make it for the class today) and ask you to try it out. 

Thanks
Shashank
